[project]
name = "bayesmbar"
version = "0.1.6"
description = "Bayesian Multistate Bennett Acceptance Ratio (BayesMBAR) methods for free energy calculations."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "blackjax[progress]>=1.6",
    "networkx>=3.0",
    "tqdm>=4.66",
    "optax>=0.2.3",
    "numpy>=2.0",
    "scipy>=1.14",
    "jax>=0.10.0",
]

[dependency-groups]
dev = [
    "ipython==8.29.0",
    "matplotlib==3.10.3",
    "mkdocstrings-python==2.0.4",
    "pytest==8.3.5",
    "zensical>=0.0.57",
]

[project.optional-dependencies]
testing = [
    "pytest==8.3.5"
]
cuda = [
    "jax[cuda12]>=0.10.0 ; sys_platform == 'linux'",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff.lint]
extend-select = ["I"]
