[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "BayesMBAR"
version = "0.0.4"
authors = [
  { name="Xinqiang Ding", email="Xinqiang.Ding@tufts.edu" }
]
description = "Bayesian Multistate Bennett Acceptance Ratio Methods"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    'optax>=0.1.9',
    'jax>=0.4.23',
    'blackjax>=1.1.1',    
    'numpy>=1.25.2',
    'scipy>=1.11.4',
    'tqdm>=4.66.2',
    'pytest>=7.4.4'
]

[project.urls]
"Homepage" = "https://bayesmbar.readthedocs.io"
"Bug Tracker" = "https://github.com/DingGroup/BayesMBAR/issues"

[tool.hatch.build]
exclude = [
  "examples/*",
]
